# Generated by Django 5.0.3 on 2024-08-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Image',
            field=models.ImageField(null=True, upload_to='Media/Profile_pic'),
        ),
    ]
